version: '3.3'
services:
    docker_bpmn:
        volumes:
            - '$XSOCK:/tmp/.X11-unix/'
            - '$XAUTH:/tmp/.docker.xauth'
        environment:
            - XAUTHORITY=/tmp/.docker.xauth
        container_name: docker_bpmn
        image: docker_bpmn
        command: java --module-path /home/admin/OpenJFX/javafx-sdk-17.0.0.1/lib --add-modules=javafx.controls,javafx.fxml -jar target/Translator-1.0-SNAPSHOT-jar-with-dependencies.jar
    clean-maven:
      working_dir: /OffChainProcessor/offchainprocessor
        #tty: true
        #stdin_open: true
      build:
        context: ./
      container_name: offchainprocessor
        #volumes:
        #- ./offchainprocessor:/target
      command: java -jar /home/admin/OffChainProcessor/offchainprocessor/target/offchainprocessor-1.0-SNAPSHOT-jar-with-dependencies.jar
